[package]
name = "enkay"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
ariadne = "0.1"
chumsky = "1.0.0-alpha.0"
thiserror = "1"
wasm-encoder = "0.20"
wasmtime = "4.0"
